/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import Threads.ThreadMusica;
import Threads.ThreadTempo;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import logicaGioco.DescrizioneGioco;

/**
 *
 * @author mtubi
 */
public class ContinuaPartita extends javax.swing.JPanel {

    /**
     * Creates new form ContinuaPartita
     */
    public ContinuaPartita(mainSwing ms) {
        this.ms = ms;
        initComponents();
        this.visualizzaPartiteSalvate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        visualizzaPartiteSalvate = new javax.swing.JTextArea();
        nomePartita = new javax.swing.JTextField();
        invio = new javax.swing.JButton();
        esci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        muta = new javax.swing.JButton();
        smuta = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        visualizzaPartiteSalvate.setColumns(20);
        visualizzaPartiteSalvate.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        visualizzaPartiteSalvate.setRows(5);
        jScrollPane1.setViewportView(visualizzaPartiteSalvate);

        nomePartita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomePartitaKeyPressed(evt);
            }
        });

        invio.setBackground(new java.awt.Color(102, 255, 102));
        invio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invio.setText("INVIO");
        invio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invioActionPerformed(evt);
            }
        });

        esci.setBackground(new java.awt.Color(255, 51, 51));
        esci.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        esci.setText("ESCI");
        esci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esciActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserire il nome della partita da continuare:\n");

        muta.setBackground(new java.awt.Color(255, 204, 102));
        muta.setText("MUTE");
        muta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutaActionPerformed(evt);
            }
        });

        smuta.setBackground(new java.awt.Color(255, 255, 102));
        smuta.setText("UNMUTE");
        smuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomePartita, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muta)
                .addGap(12, 12, 12)
                .addComponent(smuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(esci, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePartita, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(esci, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(muta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smuta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents
    private final mainSwing ms;
    private List<DescrizioneGioco> partiteSalvate = new ArrayList();
    
    private void invioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invioActionPerformed
       this.continua();
    }//GEN-LAST:event_invioActionPerformed

    private void nomePartitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomePartitaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          this.continua();
        }
    }//GEN-LAST:event_nomePartitaKeyPressed

    public void continua(){
           String np = this.nomePartita.getText();
        np = np.toLowerCase();
        int pos = -1;
        if (np.isEmpty()) {
            JOptionPane.showMessageDialog(this.ms.getFrame(), "Nome non valido", "Errore", JOptionPane.ERROR_MESSAGE);
            this.nomePartita.setText("");
        } else {
            for (DescrizioneGioco dg : partiteSalvate) {
                if (dg.getNomeGiocatore().equals(np)) {
                    pos = partiteSalvate.indexOf(dg);
                }
            }
            if (pos == -1) {
                JOptionPane.showMessageDialog(this.ms.getFrame(), "Nome non valido", "Errore", JOptionPane.ERROR_MESSAGE);
                this.nomePartita.setText("");
            } else {
                DescrizioneGioco partita = partiteSalvate.get(pos);
                partita.setSospesa(false);
                this.ms.getGiocoGui().setPartita(partita);
                this.ms.getGiocoGui().getVisualizzazioneTesto().setText("Rin: 'Ben tornato, ora ci troviamo nel " + partita.getStanzaCorrente().getNomeStanza() + "'");
                ThreadTempo.Time();
                this.nomePartita.setText("");
                this.ms.getFrame().setContentPane(this.ms.getGiocoGui());
                this.ms.getFrame().validate();
            }
        }
    }
    public void setPartiteSalvate(List<DescrizioneGioco> partiteSalvate) {
        this.partiteSalvate = partiteSalvate;
    }

    public List<DescrizioneGioco> getPartiteSalvate() {
        return partiteSalvate;
    }

 

    public JTextArea getVisualizzaPartiteSalvate() {
        return visualizzaPartiteSalvate;
    }

    public JTextField getNomePartita() {
        return nomePartita;
    }

    
    private void esciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esciActionPerformed
        this.ms.getFrame().setContentPane(this.ms.getMenuInizio());
        this.ms.getFrame().validate();
    }//GEN-LAST:event_esciActionPerformed

    private void smutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smutaActionPerformed
         ThreadMusica.setVolumeOn();
    }//GEN-LAST:event_smutaActionPerformed

    private void mutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutaActionPerformed
        ThreadMusica.setVolumeOff();
    }//GEN-LAST:event_mutaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton esci;
    private javax.swing.JButton invio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton muta;
    private javax.swing.JTextField nomePartita;
    private javax.swing.JButton smuta;
    private javax.swing.JTextArea visualizzaPartiteSalvate;
    // End of variables declaration//GEN-END:variables
}
