/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import DataBase.Db;
import com.mycompany.progettomap.giochi.Gioco;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logicaGioco.DescrizioneGioco;
import salvataggio.Deserializzazione;
import salvataggio.Serializzazione;

/**
 *
 * @author domen
 */
public class creaPartita extends javax.swing.JPanel {

    private mainSwing ms;

    /**
     * Creates new form creaPartita
     */
    public creaPartita(mainSwing ms) {
        initComponents();
        this.ms = ms;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePartita = new javax.swing.JTextField();
        confermaNome = new javax.swing.JButton();
        indietro = new javax.swing.JButton();

        confermaNome.setText("conferma");
        confermaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaNomeActionPerformed(evt);
            }
        });

        indietro.setText("indietro");
        indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(nomePartita, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confermaNome)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(indietro)
                        .addGap(156, 156, 156))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(indietro)
                .addGap(47, 47, 47)
                .addComponent(nomePartita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(confermaNome)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void indietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroActionPerformed
        this.ms.getFrame().setContentPane(this.ms.getMenuInizio());
        this.ms.getFrame().validate();
    }//GEN-LAST:event_indietroActionPerformed

    public JTextField getNomePartita() {
        return nomePartita;
    }

    
    private void confermaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaNomeActionPerformed
        List<DescrizioneGioco> l = Deserializzazione.letturaFile();
        Db db = Db.getDb();
        boolean isExiting = false;
        String nome = this.nomePartita.getText();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this.ms.getFrame(), "Nome non valido", "Errore", JOptionPane.ERROR_MESSAGE);
        } else {
            for (DescrizioneGioco g : l) {
                if (g.getNomeGiocatore().equals(nome)) {
                    isExiting = true;
                }
            }
            if (isExiting) {
                JOptionPane.showMessageDialog(this.ms.getFrame(), "Nome non valido", "Errore", JOptionPane.ERROR_MESSAGE);
            } else {
                DescrizioneGioco partita = new Gioco(nome, db.inserisci(nome, 0, false, true));
                db.chiudiConnessione();
                try {
                    Serializzazione.scriviFile(partita);
                    this.ms.getGiocoGui().setPartita(partita);
                     this.ms.getFrame().setContentPane(this.ms.getGiocoGui());
                     this.ms.getFrame().validate();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Gioco.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_confermaNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confermaNome;
    private javax.swing.JButton indietro;
    private javax.swing.JTextField nomePartita;
    // End of variables declaration//GEN-END:variables
}
